import dataclasses
from typing import List

from praktika import Workflow, Job, Artifact
from praktika.mangle import _get_workflows
from praktika.parser import WorkflowConfigParser, AddonType
from praktika.runtime import WorkflowRuntime
from praktika.utils import Utils, Shell, ContextManager
from praktika.settings import Settings


class YamlGenerator:
    class Templates:
        TEMPLATE_PULL_REQUEST_0 = """\
# generated by praktika

name: {NAME}

on:
  {EVENT}:
    branches: [{BRANCHES}]

env:
  # Force the stdout and stderr streams to be unbuffered
  PYTHONUNBUFFERED: 1

jobs:
{JOBS}\
"""

        TEMPLATE_RUN_COMMAND = """
          {COMMAND}\
"""
        TEMPLATE_JOB_0 = """
  {JOB_NAME_NORMALIZED}:
    runs-on: [{RUNS_ON}]
    needs: [{NEEDS}]{IF_EXPRESSION}
    name: {JOB_NAME}
    outputs:
      data: ${{{{ steps.run.outputs.DATA }}}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
{JOB_ADDONS}
      - name: Set up env
        run: |
{SETUP_ENVS}{EXTRA_COMMANDS}
          echo '''${{{{ needs.{WORKFLOW_CONFIG_JOB_NAME}.outputs.data }}}}''' > {WORKFLOW_CONFIG_FILE}
          cat {WORKFLOW_CONFIG_FILE}
          echo "::group::GITHUB ENV"
          env | grep GITHUB
          env | grep -q GITHUB_EVENT_PATH && cat "$GITHUB_EVENT_PATH" ||:
          echo "::endgroup::"
          echo "PRAKTIKA_STEP_ENV_OK=1" >> "$GITHUB_ENV"
{DOWNLOADS_GITHUB}
      - name: Pre
        run: |
          python -m praktika.runner --pre-run --job-name "{JOB_NAME}" --workflow-name "{WORKFLOW_NAME}"
      - name: Run
        id: run
        run: |
          python -m praktika.runner --run --job-name "{JOB_NAME}" --workflow-name "{WORKFLOW_NAME}"

      - name: Post
        if: ${{{{ !cancelled() }}}}
        run: |
          python -m praktika.runner --post-run --job-name "{JOB_NAME}" --workflow-name "{WORKFLOW_NAME}"
{UPLOADS_GITHUB}\
"""

        TEMPLATE_SETUP_ENV = """\
          rm -rf {INPUT_DIR} {OUTPUT_DIR} {TEMP_DIR}
          mkdir -p {TEMP_DIR} {INPUT_DIR} {OUTPUT_DIR} {RESULT_DIR}
          echo "TEMP_DIR=$(readlink -f {TEMP_DIR})" >> "$GITHUB_ENV"
          echo "INPUT_DIR=$(readlink -f {INPUT_DIR})" >> "$GITHUB_ENV"
          echo "OUTPUT_DIR=$(readlink -f {OUTPUT_DIR})" >> "$GITHUB_ENV"
          export GH_APP_PEM_KEY="${{{{ secrets.GH_APP_PEM_KEY }}}}"
          export GH_APP_ID="${{{{ secrets.GH_APP_ID }}}}"
          export PYTHONPATH=$(pwd)
          echo PYTHONPATH=$PYTHONPATH >> "$GITHUB_ENV"\
"""

        TEMPLATE_PY_INSTALL = """
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: {PYTHON_VERSION}
"""

        TEMPLATE_PY_WITH_REQUIREMENTS = (
            TEMPLATE_PY_INSTALL
            + """
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r {REQUIREMENT_PATH}
          #pip install praktika
"""
        )

        TEMPLATE_GH_UPLOAD = """
      - name: Upload artifact {NAME}
        uses: actions/upload-artifact@v4
        with:
          name: {NAME}
          path: {PATH}
"""

        TEMPLATE_GH_DOWNLOAD = """
      - name: Download artifact {NAME}
        uses: actions/download-artifact@v4
        with:
          name: {NAME}
          path: {PATH}
"""

        TEMPLATE_IF_EXPRESSION = """
    if: ${{{{ !failure() && !cancelled() && !contains(fromJson(needs.{WORKFLOW_CONFIG_JOB_NAME}.outputs.data).cache_success, '{JOB_NAME}') }}}}\
"""

        TEMPLATE_IF_EXPRESSION_NOT_CANCELLED = """
    if: ${{ !cancelled() }}\
"""

    def __init__(self):
        self.py_workflows = []  # type: List[Workflow.Config]

    @classmethod
    def _get_workflow_file_name(cls, workflow_name):
        return f"{Settings.WORKFLOW_PATH_PREFIX}/{Utils.normalize_string(workflow_name)}.yaml"

    def generate(self, workflow_file="", workflow_config=None):
        print("===Start generating yaml pipelines===")
        if workflow_config:
            self.py_workflows = [workflow_config]
        else:
            self.py_workflows = _get_workflows(file=workflow_file)
            assert self.py_workflows
        for workflow_config in self.py_workflows:
            print(f"Generate workflow [{workflow_config.name}]")
            parser = WorkflowConfigParser(workflow_config).parse()
            if (
                workflow_config.is_event_pull_request()
                or workflow_config.is_event_push()
            ):
                yaml_workflow_str = PullRequestPushYamlGen(parser).generate()
            else:
                assert (
                    False
                ), f"Workflow event not yet supported [{workflow_config.event}]"

            with ContextManager.cd():
                with open(self._get_workflow_file_name(workflow_config.name), "w") as f:
                    f.write(yaml_workflow_str)

        with ContextManager.cd():
            Shell.check("git add ./.github/workflows/*.yaml")


class PullRequestPushYamlGen:
    def __init__(self, parser: WorkflowConfigParser):
        self.workflow_config = parser.workflow_yaml_config
        self.parser = parser

    def generate(self):
        base_template = YamlGenerator.Templates.TEMPLATE_PULL_REQUEST_0
        template_1 = base_template.strip().format(
            NAME=self.workflow_config.name,
            BRANCHES=", ".join(
                [f"'{branch}'" for branch in self.workflow_config.branches]
            ),
            EVENT=self.workflow_config.event,
            JOBS="{}\n" * len(self.workflow_config.jobs),
        )

        job_items = []
        for i, job in enumerate(self.workflow_config.jobs):
            job_name_normalized = Utils.normalize_string(job.name)
            needs = ", ".join(map(Utils.normalize_string, job.needs))
            job_name = job.name
            job_addons = []
            for addon in job.addons:
                if addon.type == AddonType.PY:
                    if addon.path:
                        job_addons.append(
                            YamlGenerator.Templates.TEMPLATE_PY_WITH_REQUIREMENTS.format(
                                PYTHON_VERSION=Settings.PYTHON_VERSION,
                                REQUIREMENT_PATH=addon.path,
                            )
                        )
                    else:
                        job_addons.append(
                            YamlGenerator.Templates.TEMPLATE_PY_INSTALL.format(
                                PYTHON_VERSION=Settings.PYTHON_VERSION
                            )
                        )
            uploads_github = []
            for artifact in job.artifacts_gh_provides:
                uploads_github.append(
                    YamlGenerator.Templates.TEMPLATE_GH_UPLOAD.format(
                        NAME=artifact.name, PATH=artifact.path
                    )
                )
            downloads_github = []
            for artifact in job.artifacts_gh_requires:
                downloads_github.append(
                    YamlGenerator.Templates.TEMPLATE_GH_DOWNLOAD.format(
                        NAME=artifact.name, PATH=Settings.INPUT_DIR
                    )
                )

            config_job_name_normalized = Utils.normalize_string(
                Settings.CI_CONFIG_JOB_NAME
            )

            if_expression = ""
            if (
                self.workflow_config.enable_cache
                and job_name_normalized != config_job_name_normalized
            ):
                if_expression = YamlGenerator.Templates.TEMPLATE_IF_EXPRESSION.format(
                    WORKFLOW_CONFIG_JOB_NAME=config_job_name_normalized,
                    JOB_NAME=job_name,
                )
            if job.run_if_not_cancelled:
                if_expression = (
                    YamlGenerator.Templates.TEMPLATE_IF_EXPRESSION_NOT_CANCELLED
                )

            extra_cmds = ""
            if job.gh_app_auth:
                extra_cmds = YamlGenerator.Templates.TEMPLATE_RUN_COMMAND.format(
                    COMMAND="python3 -m praktika.gh_auth"
                )
            setup_envs = YamlGenerator.Templates.TEMPLATE_SETUP_ENV.format(
                TEMP_DIR=Settings.TEMP_DIR,
                INPUT_DIR=Settings.INPUT_DIR,
                OUTPUT_DIR=Settings.OUTPUT_DIR,
                RESULT_DIR=Settings.RESULTS_DIR,
            )

            job_item = YamlGenerator.Templates.TEMPLATE_JOB_0.format(
                JOB_NAME_NORMALIZED=job_name_normalized,
                WORKFLOW_CONFIG_JOB_NAME=config_job_name_normalized,
                IF_EXPRESSION=if_expression,
                RUNS_ON=", ".join(job.runs_on),
                NEEDS=needs,
                JOB_NAME=job_name,
                WORKFLOW_NAME=self.workflow_config.name,
                SETUP_ENVS=setup_envs,
                EXTRA_COMMANDS=extra_cmds,
                WORKFLOW_CONFIG_FILE=WorkflowRuntime.file_name_static(
                    self.workflow_config.name
                ),
                JOB_ADDONS="\n".join(job_addons),
                DOWNLOADS_GITHUB="\n".join(downloads_github),
                UPLOADS_GITHUB="\n".join(uploads_github),
            )
            job_items.append(job_item.rstrip("\n"))
        res = template_1.format(*job_items)

        return res


@dataclasses.dataclass
class AuxConfig:
    # defines aux step to install dependencies
    addon: Job.Requirements
    # defines aux step(s) to upload GH artifacts
    uploads_gh: List[Artifact.Config]
    # defines aux step(s) to download GH artifacts
    downloads_gh: List[Artifact.Config]

    def get_aux_workflow_name(self):
        suffix = ""
        if self.addon.python_requirements_txt:
            suffix += "_py"
        for _ in self.uploads_gh:
            suffix += "_uplgh"
        for _ in self.downloads_gh:
            suffix += "_dnlgh"
        return f"{Settings.WORKFLOW_PATH_PREFIX}/aux_job{suffix}.yaml"

    def get_aux_workflow_input(self):
        res = ""
        if self.addon.python_requirements_txt:
            res += f"      requirements_txt: {self.addon.python_requirements_txt}"
        return res


if __name__ == "__main__":
    WFS = [
        Workflow.Config(
            name="PR",
            event=Workflow.Event.PULL_REQUEST,
            jobs=[
                Job.Config(
                    name="Hello World",
                    runs_on=["foo"],
                    command="bar",
                    job_requirements=Job.Requirements(
                        python_requirements_txt="./requirement.txt"
                    ),
                )
            ],
            enable_cache=True,
        )
    ]
    YamlGenerator().generate(workflow_config=WFS)
