name: Example Self-hosted Runners

on:
  pull_request:
    branches:
      - main

jobs:

  job_a:
    runs-on: [maxs-small]
    needs: []
    name: Job A
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up env
        run: |
          rm -rf ~/lh_ci/input ~/lh_ci/output ~/lh_ci
          mkdir -p ~/lh_ci ~/lh_ci/input ~/lh_ci/output
          echo "TEMP_DIR=$(readlink -f ~/lh_ci)" >> "$GITHUB_ENV"
          echo "INPUT_DIR=$(readlink -f ~/lh_ci/input)" >> "$GITHUB_ENV"
          echo "OUTPUT_DIR=$(readlink -f ~/lh_ci/output)" >> "$GITHUB_ENV"
          env | grep GITHUB

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          #pip install recurcipy

      - name: Pre
        run: |
          python -m recurcipy.runner --pre-run --job-name "Job A" --workflow-name "Example Self-hosted Runners"

      - name: Run
        run: |
          python -m recurcipy.runner --run --job-name "Job A" --workflow-name "Example Self-hosted Runners"

      - name: Post
        run: |
          python -m recurcipy.runner --post-run --job-name "Job A" --workflow-name "Example Self-hosted Runners"

  job_b:
    runs-on: [maxs-small]
    needs: []
    name: Job B
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up env
        run: |
          rm -rf ~/lh_ci/input ~/lh_ci/output ~/lh_ci
          mkdir -p ~/lh_ci ~/lh_ci/input ~/lh_ci/output
          echo "TEMP_DIR=$(readlink -f ~/lh_ci)" >> "$GITHUB_ENV"
          echo "INPUT_DIR=$(readlink -f ~/lh_ci/input)" >> "$GITHUB_ENV"
          echo "OUTPUT_DIR=$(readlink -f ~/lh_ci/output)" >> "$GITHUB_ENV"
          env | grep GITHUB

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          #pip install recurcipy

      - name: Pre
        run: |
          python -m recurcipy.runner --pre-run --job-name "Job B" --workflow-name "Example Self-hosted Runners"

      - name: Run
        run: |
          python -m recurcipy.runner --run --job-name "Job B" --workflow-name "Example Self-hosted Runners"

      - name: Post
        run: |
          python -m recurcipy.runner --post-run --job-name "Job B" --workflow-name "Example Self-hosted Runners"
