name: Example Job Dependencies

on:
  pull_request:
    branches:
      - main

jobs:

  job_a_starting_at_the_beginning:
    runs-on: [ubuntu-latest]
    needs: []
    name: Job A starting at the beginning
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up env
        run: |
          rm -rf ~/lh_ci/input ~/lh_ci/output ~/lh_ci
          mkdir -p ~/lh_ci ~/lh_ci/input ~/lh_ci/output
          echo "TEMP_DIR=$(readlink -f ~/lh_ci)" >> "$GITHUB_ENV"
          echo "INPUT_DIR=$(readlink -f ~/lh_ci/input)" >> "$GITHUB_ENV"
          echo "OUTPUT_DIR=$(readlink -f ~/lh_ci/output)" >> "$GITHUB_ENV"
          env | grep GITHUB

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          #pip install recurcipy

      - name: Pre
        run: |
          python -m recurcipy.runner --pre-run --job-name "Job A starting at the beginning" --workflow-name "Example Job Dependencies"

      - name: Run
        run: |
          python -m recurcipy.runner --run --job-name "Job A starting at the beginning" --workflow-name "Example Job Dependencies"

      - name: Post
        run: |
          python -m recurcipy.runner --post-run --job-name "Job A starting at the beginning" --workflow-name "Example Job Dependencies"

  job_b_starting_at_the_beginning:
    runs-on: [ubuntu-latest]
    needs: []
    name: Job B starting at the beginning
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up env
        run: |
          rm -rf ~/lh_ci/input ~/lh_ci/output ~/lh_ci
          mkdir -p ~/lh_ci ~/lh_ci/input ~/lh_ci/output
          echo "TEMP_DIR=$(readlink -f ~/lh_ci)" >> "$GITHUB_ENV"
          echo "INPUT_DIR=$(readlink -f ~/lh_ci/input)" >> "$GITHUB_ENV"
          echo "OUTPUT_DIR=$(readlink -f ~/lh_ci/output)" >> "$GITHUB_ENV"
          env | grep GITHUB

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          #pip install recurcipy

      - name: Pre
        run: |
          python -m recurcipy.runner --pre-run --job-name "Job B starting at the beginning" --workflow-name "Example Job Dependencies"

      - name: Run
        run: |
          python -m recurcipy.runner --run --job-name "Job B starting at the beginning" --workflow-name "Example Job Dependencies"

      - name: Post
        run: |
          python -m recurcipy.runner --post-run --job-name "Job B starting at the beginning" --workflow-name "Example Job Dependencies"

  job_c_starting_after_job_a_and_b_is_done:
    runs-on: [ubuntu-latest]
    needs: [job_a_starting_at_the_beginning, job_b_starting_at_the_beginning]
    name: Job C starting after Job A and B is done
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up env
        run: |
          rm -rf ~/lh_ci/input ~/lh_ci/output ~/lh_ci
          mkdir -p ~/lh_ci ~/lh_ci/input ~/lh_ci/output
          echo "TEMP_DIR=$(readlink -f ~/lh_ci)" >> "$GITHUB_ENV"
          echo "INPUT_DIR=$(readlink -f ~/lh_ci/input)" >> "$GITHUB_ENV"
          echo "OUTPUT_DIR=$(readlink -f ~/lh_ci/output)" >> "$GITHUB_ENV"
          env | grep GITHUB

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          #pip install recurcipy

      - name: Pre
        run: |
          python -m recurcipy.runner --pre-run --job-name "Job C starting after Job A and B is done" --workflow-name "Example Job Dependencies"

      - name: Run
        run: |
          python -m recurcipy.runner --run --job-name "Job C starting after Job A and B is done" --workflow-name "Example Job Dependencies"

      - name: Post
        run: |
          python -m recurcipy.runner --post-run --job-name "Job C starting after Job A and B is done" --workflow-name "Example Job Dependencies"

  job_d_starting_after_job_c_is_done:
    runs-on: [ubuntu-latest]
    needs: [job_c_starting_after_job_a_and_b_is_done]
    name: Job D starting after Job C is done
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up env
        run: |
          rm -rf ~/lh_ci/input ~/lh_ci/output ~/lh_ci
          mkdir -p ~/lh_ci ~/lh_ci/input ~/lh_ci/output
          echo "TEMP_DIR=$(readlink -f ~/lh_ci)" >> "$GITHUB_ENV"
          echo "INPUT_DIR=$(readlink -f ~/lh_ci/input)" >> "$GITHUB_ENV"
          echo "OUTPUT_DIR=$(readlink -f ~/lh_ci/output)" >> "$GITHUB_ENV"
          env | grep GITHUB

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          #pip install recurcipy

      - name: Pre
        run: |
          python -m recurcipy.runner --pre-run --job-name "Job D starting after Job C is done" --workflow-name "Example Job Dependencies"

      - name: Run
        run: |
          python -m recurcipy.runner --run --job-name "Job D starting after Job C is done" --workflow-name "Example Job Dependencies"

      - name: Post
        run: |
          python -m recurcipy.runner --post-run --job-name "Job D starting after Job C is done" --workflow-name "Example Job Dependencies"
