name: Example On Push, S3, sh

on:
  push:
    branches: [parse_gh_env, test**]

jobs:

  job_a:
    runs-on: [maxs-small]
    needs: []
    name: Job A
    outputs:
      data: ${{ steps.run.outputs.DATA }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up env
        run: |
          rm -rf /tmp/tmp_ci/input /tmp/tmp_ci/output /tmp/tmp_ci
          mkdir -p /tmp/tmp_ci /tmp/tmp_ci/input /tmp/tmp_ci/output
          echo "TEMP_DIR=$(readlink -f /tmp/tmp_ci)" >> "$GITHUB_ENV"
          echo "INPUT_DIR=$(readlink -f /tmp/tmp_ci/input)" >> "$GITHUB_ENV"
          echo "OUTPUT_DIR=$(readlink -f /tmp/tmp_ci/output)" >> "$GITHUB_ENV"
          echo '''${{ needs.workflowconfig.outputs.data }}''' > /tmp/workflow_config.json
          cat /tmp/workflow_config.json
          env | grep GITHUB
          env | grep -q GITHUB_EVENT_PATH && cat "$GITHUB_EVENT_PATH" ||:

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          #pip install recurcipy

      - name: Pre
        run: |
          python -m recurcipy.runner --pre-run --job-name "Job A" --workflow-name "Example On Push, S3, sh"

      - name: Run
        id: run
        run: |
          python -m recurcipy.runner --run --job-name "Job A" --workflow-name "Example On Push, S3, sh"

      - name: Post
        run: |
          python -m recurcipy.runner --post-run --job-name "Job A" --workflow-name "Example On Push, S3, sh"

  job_b:
    runs-on: [maxs-small]
    needs: [job_a]
    name: Job B
    outputs:
      data: ${{ steps.run.outputs.DATA }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up env
        run: |
          rm -rf /tmp/tmp_ci/input /tmp/tmp_ci/output /tmp/tmp_ci
          mkdir -p /tmp/tmp_ci /tmp/tmp_ci/input /tmp/tmp_ci/output
          echo "TEMP_DIR=$(readlink -f /tmp/tmp_ci)" >> "$GITHUB_ENV"
          echo "INPUT_DIR=$(readlink -f /tmp/tmp_ci/input)" >> "$GITHUB_ENV"
          echo "OUTPUT_DIR=$(readlink -f /tmp/tmp_ci/output)" >> "$GITHUB_ENV"
          echo '''${{ needs.workflowconfig.outputs.data }}''' > /tmp/workflow_config.json
          cat /tmp/workflow_config.json
          env | grep GITHUB
          env | grep -q GITHUB_EVENT_PATH && cat "$GITHUB_EVENT_PATH" ||:

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          #pip install recurcipy

      - name: Pre
        run: |
          python -m recurcipy.runner --pre-run --job-name "Job B" --workflow-name "Example On Push, S3, sh"

      - name: Run
        id: run
        run: |
          python -m recurcipy.runner --run --job-name "Job B" --workflow-name "Example On Push, S3, sh"

      - name: Post
        run: |
          python -m recurcipy.runner --post-run --job-name "Job B" --workflow-name "Example On Push, S3, sh"
