name: GitHub Artifact Example

on:
  pull_request:
    branches:
      - main

jobs:

  provide_artifact:
    runs-on: ubuntu-latest
    needs: []
    name: Provide Artifact
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up env
        run: |
          rm -rf ~/lh_ci/input ~/lh_ci/output ~/lh_ci
          mkdir -p ~/lh_ci ~/lh_ci/input ~/lh_ci/output
          echo "TEMP_DIR=$(readlink -f ~/lh_ci)" >> "$GITHUB_ENV"
          echo "INPUT_DIR=$(readlink -f ~/lh_ci/input)" >> "$GITHUB_ENV"
          echo "OUTPUT_DIR=$(readlink -f ~/lh_ci/output)" >> "$GITHUB_ENV"
          env | grep GITHUB

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          #pip install recurcipy

      - name: Pre
        run: |
          python -m recurcipy.runner --pre-run --job-name "Provide Artifact" --workflow-name "GitHub Artifact Example"

      - name: Run
        run: |
          python -m recurcipy.runner --run --job-name "Provide Artifact" --workflow-name "GitHub Artifact Example"

      - name: Post
        run: |
          python -m recurcipy.runner --post-run --job-name "Provide Artifact" --workflow-name "GitHub Artifact Example"

      - name: Upload artifact greet
        uses: actions/upload-artifact@v3
        with:
          name: greet
          path: ./hello_world.txt

  consume_artifact:
    runs-on: ubuntu-latest
    needs: [provide_artifact]
    name: Consume Artifact
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up env
        run: |
          rm -rf ~/lh_ci/input ~/lh_ci/output ~/lh_ci
          mkdir -p ~/lh_ci ~/lh_ci/input ~/lh_ci/output
          echo "TEMP_DIR=$(readlink -f ~/lh_ci)" >> "$GITHUB_ENV"
          echo "INPUT_DIR=$(readlink -f ~/lh_ci/input)" >> "$GITHUB_ENV"
          echo "OUTPUT_DIR=$(readlink -f ~/lh_ci/output)" >> "$GITHUB_ENV"
          env | grep GITHUB

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          #pip install recurcipy

      - name: Download artifact greet
        uses: actions/download-artifact@v3
        with:
          name: greet
          path: ~/lh_ci/input

      - name: Pre
        run: |
          python -m recurcipy.runner --pre-run --job-name "Consume Artifact" --workflow-name "GitHub Artifact Example"

      - name: Run
        run: |
          python -m recurcipy.runner --run --job-name "Consume Artifact" --workflow-name "GitHub Artifact Example"

      - name: Post
        run: |
          python -m recurcipy.runner --post-run --job-name "Consume Artifact" --workflow-name "GitHub Artifact Example"
